apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  generation: 1
  labels:
    run: ccloud-poc
  name: ccloud-poc
  selfLink: /apis/apps.openshift.io/v1/namespaces/ccloud-poc/deploymentconfigs/ccloud-poc
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    run: ccloud-poc
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: ccloud-poc
    spec:
      containers:
      - args:
        - cd /usr/app ; mvn clean package ; mvn -Dmaven.repo.local=/root/.m2/repository
          exec:java -Dexec.mainClass="io.confluent.examples.clients.cloud.ProducerExample"
          -Dexec.args="/root/.ccloud/config test1"
        command:
        - /bin/sh
        - -c
        image: rajeshd2090/ccloud:6
        imagePullPolicy: IfNotPresent
        name: ccloud-poc
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
